[build]
  # For Hospital Portal
  command = "cd Hospital && npm run build"
  publish = "Hospital/dist"

[build.environment]
  NODE_VERSION = "18"

# SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects to backend (when you deploy backend)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/api/:splat"
  status = 200

# Headers for better performance  
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"