# Netlify Configuration for Patient Portal
[build]
  command = "npm install && npm run build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "18"

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200